config/routes.rb
Rails.application.routes.draw do
  resources :top_sites do
    put :sort, on: :collection
  end
  get 'scrap_alexa', to: 'top_sites#scrap'

  get 'records', to:'statistics#get_urls'
  get 'retrieve', to:'statistics#get_tracking_for_url'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  
  root 'top_sites#index'

end

app/models/screen_capturer.rb
require 'screencap'
class ScreenCapturer
	def self.capture(url)
		fetcher_object = Screencap::Fetcher.new(url)
		screenshot = fetcher_object.fetch(
		    output: 'app/assets/images/'+url+'.png',
		    width: 1024, 
		    height: 768, 
		    top: 0, left: 0, width: 100, height: 100 
	  	)
	end

end

app/models/top_site.rb
class TopSite < ActiveRecord::Base
	

	def self.search(query)
    	# where(:title, query) -> This would return an exact match of the query
    	where("lower(name) like ?", "%#{query.downcase}%") 
  	end
end

app/models/tracking.rb
require 'mongo'
class Tracking
	@client
	def initialize()
		@client = Mongo::Client.new('mongodb://127.0.0.1:27017/short_link_db')
	end

	def find()
		@client[:track].aggregate([{:$group => { :_id => "$longUrl", "total_clicks" => { :$sum => "$count"}}}]).each{|d| puts d}
	end

	def findBy(url)
		@client[:track].find({"longUrl" => /url/})
	end

	def getUrls
		@client[:track].find().map{|e| e["longUrl"]}
	end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
	
	def get_urls 
		@data = Mongo::Client.new('mongodb://127.0.0.1:27017/short_link_db')[:track].find()
	end

	def get_tracking_for_url
		@data = Mongo::Client.new('mongodb://127.0.0.1:27017/short_link_db')[:track].find({"longUrl" => params[:url]}).map{|e| e}
	end
end

app/controllers/top_sites_controller.rb
class TopSitesController < ApplicationController
  before_action :set_top_site, only: [:show, :edit, :update, :destroy]

  def scrap
    AlexaWorker.perform_async("alexaJob",1)
    redirect_to :root
  end

  # GET /top_sites
  # GET /top_sites.json
  def index
    sorting = params[:sort_by]
    sorting ||= "rank"

    if params[:search]
      @top_sites = TopSite.search(params[:search]).order(sorting).page(params[:page]).per(25)
    else
      @top_sites = TopSite.all.order(sorting).page(params[:page]).per(25)
    end
  end

  def sort
    params[:order].each do |key,value|
      TopSite.find(value[:id]).update_attribute(:ordering,value[:position])
    end
    render :nothing => true
  end

  # GET /top_sites/1
  # GET /top_sites/1.json
  def show
  end

  # GET /top_sites/new
  def new
    @top_site = TopSite.new
  end

  # GET /top_sites/1/edit
  def edit

  end

  # POST /top_sites
  # POST /top_sites.json
  def create
    @top_site = TopSite.new(top_site_params)

    respond_to do |format|
      if @top_site.save
        format.html { redirect_to @top_site, notice: 'Top site was successfully created.' }
        format.json { render json: @top_site, status: :created }
      else
        format.html { render :new }
        format.json { render json: @top_site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /top_sites/1
  # PATCH/PUT /top_sites/1.json
  def update
    respond_to do |format|
      if @top_site.update(top_site_params)
        format.html { redirect_to top_sites_url , notice: 'Top site was successfully updated.' }
        format.json { render json: @top_site , status: :ok }
      else
        format.html { render :edit }
        format.json { render json: @top_site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /top_sites/1
  # DELETE /top_sites/1.json
  def destroy
    @top_site.destroy
    respond_to do |format|
      format.html { redirect_to top_sites_url, notice: 'Top site was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_top_site
      @top_site = TopSite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def top_site_params
      params.require(:top_site).permit(:name, :url, :rank, :ordering)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/statistics_helper.rb
module StatisticsHelper

	def browerName(ua)
		Browser.new(:ua => ua).name
	end

	def sanitize(lang)
		lang.split(",").first
	end
end

app/helpers/top_sites_helper.rb
module TopSitesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BuzzStarter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/statistics/get_tracking_for_url.html.erb
<div id="statistics-body">
<ul class="list-group">
	 <li class="list-group-item disabled">
        <div class="row">
            
          <div class="col-md-3">
          </div>
          <div class="col-md-3">url
          </div>
          <div class="col-md-3">browser
          </div>
          <div class="col-md-3">
          </div>
      </div>
      
      </li>
<%  @data.each do |entry| %>
  <li class="list-group-item">
          <div class="row">
            <div class="col-md-3"  ><%= entry["time"] %></div>
            <div class="col-md-3"  ><%= entry["longUrl"] %></div>
            <div class="col-md-3"  ><%= browerName(entry["userAgent"]) %></div>
           	<div class="col-md-3"  ><%= entry["count"] %></div>
          </div>     
      </li>
<% end %>
</ul>
</div>

app/views/statistics/get_urls.html.erb
<div id="statistics-body">
<ul class="list-group">
	 <li class="list-group-item disabled">
        <div class="row">
          <div class="col-md-3">url
          </div>
          <div class="col-md-3">browser
          </div>
		  <div class="col-md-3">language
          </div>
          <div class="col-md-3">clicks
          </div>
      </div>
      
<%  @data.each do |entry| %>
  <li class="list-group-item">
          <div class="row">

            <div class="col-md-3"  > <%= link_to entry["longUrl"], retrieve_path( :url => entry["longUrl"]) %></div>
            <div class="col-md-3"  ><%= browerName(entry["userAgent"]) %></div>
            <div class="col-md-3"  ><%= sanitize(entry["lang"]) %></div>
           	<div class="col-md-3"  ><%= entry["count"] %></div>
           	<div class="col-md-3"  ><%= entry["time"] %></div>
          </div>     
      </li>
<% end %>
</ul>
</div>

app/views/top_sites/_form.html.erb
<%= form_for @top_site, :html => { :id => "form" , :class => "form-horizontal top_site" }, :remote => true do |f| %>

  <% if @top_site.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@top_site.errors.count, "error") %> prohibited this top_site from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @top_site.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :url, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :url, :class => 'form-control' %>
    </div>
    <%=f.error_span(:url) %>
  </div>
  <div class="form-group">
    <%= f.label :rank, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :rank, :class => 'form-control' %>
    </div>
    <%=f.error_span(:rank) %>
  </div>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <a href="#" class='btn btn-primary' onclick="submit()">Update</a>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                top_sites_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/top_sites/edit.js.erb
$(".modal-content").html("<%= j render "new"%>");
$('#modal_edit').modal('show');

app/views/top_sites/index.html.erb
<div id="top-sites-body">
  <%- model_class = TopSite -%>
  <div class="page-header">
    <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
    <%= form_tag(top_sites_path, :method => "get", class: "input-group", id: "search-form") do %>
    <div class="input-append">
      <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search Top Sites" %> <br \><br \>
      <button class="btn btn-default" type="submit">Search</button>
    </div>
  <% end %>
  </div>
  <ul class="list-group sortable">
    
      <li class="list-group-item disabled">
        <div class="row ">
            
          <div class="col-md-3">
            <%= link_to top_sites_path(:search => params[:search], :sort_by => "rank") do %>
            <%= model_class.human_attribute_name(:rank) %>
            <% end %>
          </div>
          <div class="col-md-3">
            <%= link_to top_sites_path(:search => params[:search], :sort_by => "name") do %>
            <%= model_class.human_attribute_name(:name) %>
            <% end %>
          </div>
          <div class="col-md-6">
            <%= link_to top_sites_path(:search => params[:search], :sort_by => "url") do %>
            <%= model_class.human_attribute_name(:url) %>
            <% end %>
          </div>
      </div>
      
      </li>
      
      <% @top_sites.each do |top_site| %>
        <li class="list-group-item">
          
            <div class="row">
              <a href="<%=  edit_top_site_path(top_site) %>" data-remote="true" style="none" class="">
              <div class="col-md-3" data-name='rank' data-id="<%= top_site.id %>"><%= top_site.rank %></div>
              <div class="col-md-3" data-name='name' data-id="<%= top_site.id %>" ><%= top_site.name %></div>
              <div class="col-md-6" data-name='url' data-id="<%= top_site.id %>"><%= "http://alexa.com"+top_site.url %></div>
              </a> 
            </div>
          
        </li>
      <% end %>  
  </ul>
  <%= paginate @top_sites %>
</div>

<div id="modal_edit" class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
    </div>
  </div>
</div>

app/views/top_sites/show.html.erb
<%- model_class = TopSite -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @top_site.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:url) %>:</strong></dt>
  <dd><%= @top_site.url %></dd>
  <dt><strong><%= model_class.human_attribute_name(:rank) %>:</strong></dt>
  <dd><%= @top_site.rank %></dd>
  <dt><strong><%= model_class.human_attribute_name(:ordering) %>:</strong></dt>
  <dd><%= @top_site.ordering %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              top_sites_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_top_site_path(@top_site), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              top_site_path(@top_site),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>